# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1c89fe5e21b347674bf339b3654f670168c1ea183a02143b0b93a6363b4e4e0abc2a579f60cfdd5de46df8dd0380f73139fa431a5dab82f52382c14131b7290e

test:
  secret_key_base: 79543bec5c0c5b4ba8f17d3af8068a110e24f1f111bbfe5f88fedb77d696fa0a16ade9aa248808e19ac712f43504d80987fc25fbd46450444b6cfad3f41b7bc1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
